# Generated by Django 4.0.3 on 2022-04-05 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='page_app.author', verbose_name='Author'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_by',
        ),
        migrations.AddField(
            model_name='book',
            name='published_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_app.publication', verbose_name='Publication'),
        ),
    ]
